# Copyright (c) 2025 Clove Twilight
# Licensed under the MIT License
# WingSync

discord:
  token: "YOUR_DISCORD_BOT_TOKEN"
  admin_id: "YOUR_DISCORD_ADMIN_ID"

  mysql:
    enabled: false # Change me to true to use MySql
    host: localhost
    database: minecraft
    username: root
    password: password123
    port: 3306

  plugin:
    messages:
      enabled: "WhitelistPlugin has been enabled!"
      disabled: "WhitelistPlugin has been disabled!"
      whitelist_added: "Player {player} has been added to the whitelist by {user}."
      whitelist_removed: "Player {player} has been removed from the whitelist by {user}."
      no_permission: "You do not have permission to perform this action."